# Generated by Django 5.0.6 on 2024-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dietplan_pregnancyrisk_contraction_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraction',
            name='duration',
            field=models.IntegerField(help_text='Duration of the contraction in seconds.'),
        ),
    ]
